services:
  - type: web
    name: context-graph-explorer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONPATH
        value: .
      - key: STREAMLIT_SERVER_HEADLESS
        value: true